{% set name = "protobuf-py" %}
{% set version = "0.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9a3e424e89c75121c8c66e37349dd568893c26b4917e53ca558c68c2ee641474

build:
  skip: True  # [py<310 or (osx and x86_64)]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - uv-build >=0.12.1,<0.13
    - pip
  run:
    - python
    - protobuf-py-ext ==0.4.0
    - typing_extensions >=4.13.0

test:
  imports:
    - protobuf
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/bufbuild/protobuf-py
  summary: Idiomatic Protocol Buffers for Python.
  doc_url: https://protobufpy.com/
  dev_url: https://github.com/bufbuild/protobuf-py
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - imykhailov
